---
cache: cargo
dist: xenial
env:
  global:
    - CRATE_NAME=ngraph
install:
  - "source ~/.cargo/env || true"
language: rust
env:
  - TARGET=x86_64-unknown-linux-gnu
  - NGRAPH_CPU_ENABLE=OFF
notifications:
  email:
    on_success: never
script:
  - "travis_wait 30 cargo build --examples"
  - "travis_wait 30 cargo test"
  - "travis_wait 30 cargo run --example add"
sudo: required
