---
cache: cargo
dist: xenial
env: 
  global: 
    - CRATE_NAME=ngraph
install: 
  - "source ~/.cargo/env || true"
  - "wget --no-check-certificate https://drive.google.com/open?id=1n4YwBj5AHRMUlJwyQwxyWP-4Q34RG5YL -O ngraph-build"
  - "cd ngraph-build"
  - "sudo make install"
language: rust
env: TARGET=x86_64-unknown-linux-gnu
notifications: 
  email: 
    on_success: never
script:
  - "cd $TRAVIS_BUILD_DIR"
  - "cargp build --examples"
  - "cargo test"
  - "cargo run --example computation_example"
sudo: required
