---
cache: cargo
dist: xenial
env: 
  global: 
    - CRATE_NAME=ngraph
install: 
  - "source ~/.cargo/env || true"
language: rust
env: TARGET=x86_64-unknown-linux-gnu
notifications: 
  email: 
    on_success: never
script: 
  - "git clone https://github.com/NervanaSystems/ngraph"
sudo: required
