---
cache: cargo
dist: xenial
env: 
  global: 
    - CRATE_NAME=ngraph
install: 
  - "source ~/.cargo/env || true"
  - "wget wget --no-check-certificate https://drive.google.com/open?id=1kQlEjpxWoJ3rmbbhcx6qSS6vbahILh8r -O ngraph_20190525-1_amd64.deb"
  - "sudo dpkg -i ngraph_20190525-1_amd64.deb"
language: rust
env: TARGET=x86_64-unknown-linux-gnu
notifications: 
  email: 
    on_success: never
script:
  - "cd $TRAVIS_BUILD_DIR"
  - "cargp build --examples"
  - "cargo test"
  - "cargo run --example computation_example"
sudo: required
